<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.1.0</Version>
    <Authors>Saithis</Authors>
    <PackageProjectUrl>https://github.com/saithis/Ratatoskr</PackageProjectUrl>
    <RepositoryUrl>https://github.com/saithis/Ratatoskr</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None
      Include="$(MSBuildThisFileDirectory)images/icon.png"
      Pack="true"
      PackagePath="\"
      Condition="'$(IsPackable)' == 'true' and Exists('$(MSBuildThisFileDirectory)images/icon.png')"
    />
  </ItemGroup>

  <ItemGroup Condition="'$(MSBuildProjectExtension)' == '.csproj'">
    <PackageReference
      Include="StyleCop.Analyzers"
      PrivateAssets="all"
      IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive"
    />
    <PackageReference
      Include="IDisposableAnalyzers"
      PrivateAssets="all"
      IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive"
    />
    <PackageReference
      Include="Roslynator.Analyzers"
      PrivateAssets="all"
      IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive"
    />
    <PackageReference
      Include="Microsoft.VisualStudio.Threading.Analyzers"
      PrivateAssets="all"
      IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive"
    />
    <PackageReference
      Include="AsyncUsageAnalyzers"
      PrivateAssets="all"
      IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive"
    />
    <PackageReference
      Include="Roslyn.Analyzers"
      PrivateAssets="all"
      IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive"
    />
  </ItemGroup>
</Project>
