// Provider-neutral by construction. The generated file carried SQLite store types
// (`type: "TEXT"`, `.HasColumnType("TEXT")`); those were removed so each provider's type mapper
// decides — otherwise a Guid primary key would become a text column on PostgreSQL. Re-apply the
// same edit if this migration is ever regenerated.

// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ratatoskr.UI.Store;

#nullable disable

namespace Ratatoskr.UI.Store.Migrations
{
    [DbContext(typeof(RatatoskrDashboardDbContext))]
    [Migration("20260912172314_InitialDashboardSchema")]
    partial class InitialDashboardSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Ratatoskr.UI.Store.DashboardAuditEntry", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Actor")
                        .HasMaxLength(400);

                    b.Property<string>("ActorDisplayName")
                        .HasMaxLength(400);

                    b.Property<DateTimeOffset>("CompletedAt");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100);

                    b.Property<string>("InstanceId")
                        .HasMaxLength(200);

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid>("OperationId");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("RequestJson");

                    b.Property<string>("Resource")
                        .HasMaxLength(200);

                    b.Property<string>("ResultJson");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTimeOffset>("StartedAt");

                    b.Property<string>("TransportName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex(new[] { "OperationId" }, "IX_RatatoskrDashboardAudit_OperationId");

                    b.HasIndex(new[] { "StartedAt" }, "IX_RatatoskrDashboardAudit_StartedAt");

                    b.ToTable("RatatoskrDashboardAudit", (string)null);
                });

            modelBuilder.Entity("Ratatoskr.UI.Store.DashboardServiceSnapshot", b =>
                {
                    b.Property<string>("TransportName")
                        .HasMaxLength(100);

                    b.Property<string>("ServiceName")
                        .HasMaxLength(200);

                    b.Property<string>("InstanceId")
                        .HasMaxLength(200);

                    b.Property<DateTimeOffset>("AnnouncedAt");

                    b.Property<string>("AnnouncementJson")
                        .IsRequired();

                    b.Property<DateTimeOffset>("FirstSeenAt");

                    b.Property<DateTimeOffset>("LastSeenAt");

                    b.HasKey("TransportName", "ServiceName", "InstanceId");

                    b.HasIndex(new[] { "LastSeenAt" }, "IX_RatatoskrDashboardServices_LastSeenAt");

                    b.ToTable("RatatoskrDashboardServices", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
