<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Verify.TUnit" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.RabbitMq" />
    <PackageReference Include="RabbitMQ.Client" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="DistributedLock.FileSystem" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\examples\InventoryService\InventoryService.csproj" />
    <ProjectReference Include="..\..\examples\PlaygroundHost\PlaygroundHost.csproj" />
    <ProjectReference Include="..\..\src\Ratatoskr\Ratatoskr.csproj" />
    <ProjectReference Include="..\..\src\Ratatoskr.EfCore\Ratatoskr.EfCore.csproj" />
    <ProjectReference Include="..\..\src\Ratatoskr.RabbitMq\Ratatoskr.RabbitMq.csproj" />
    <ProjectReference Include="..\..\src\Ratatoskr.Testing\Ratatoskr.Testing.csproj" />
    <ProjectReference Include="..\Ratatoskr.TestHost\Ratatoskr.TestHost.csproj" />
  </ItemGroup>
</Project>
