<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Embedded web management dashboard for Ratatoskr CloudEventBus.</Description>
    <PackageTags>cloudevents;eventbus;ui;dashboard;management;ratatoskr</PackageTags>
    <IsPackable>true</IsPackable>
    <NoWarn>$(NoWarn);1591;CA1848;CA1873;MA0051;MA0007;MA0046;RCS1238;MA0003</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="wwwroot\**\*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ratatoskr.Management\Ratatoskr.Management.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Ratatoskr.Tests" />
  </ItemGroup>
</Project>
