<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Embedded Web Management Dashboard for Ratatoskr.</Description>
    <PackageTags>cloudevents;eventbus;messaging;dashboard;ui;aspnetcore</PackageTags>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ratatoskr\Ratatoskr.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="wwwroot\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MinVer">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Ratatoskr.Tests" />
  </ItemGroup>
</Project>
