<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsPackable>false</IsPackable>
        <WarnOnPackingNonPackableProject>false</WarnOnPackingNonPackableProject>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
      <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
      <PackageReference Include="Microsoft.Extensions.ServiceDiscovery" />
      <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
      <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
      <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
      <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
      <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
      <PackageReference Include="DistributedLock.FileSystem" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Ratatoskr.EfCore\Ratatoskr.EfCore.csproj" />
      <ProjectReference Include="..\..\src\Ratatoskr.RabbitMq\Ratatoskr.RabbitMq.csproj" />
      <ProjectReference Include="..\..\src\Ratatoskr\Ratatoskr.csproj" />
    </ItemGroup>

</Project>
